name: foundation_fluttify
description: Foundation for `Fluttify`.
version: 0.12.0-dev.0
authors:
  - yohom <yohombao@qq.com>
homepage: https://github.com/fluttify-project/foundation_fluttify

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=1.10.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.9.2

flutter:
  plugin:
    platforms:
      android:
        package: me.yohom.foundation_fluttify
        pluginClass: FoundationFluttifyPlugin
      ios:
        pluginClass: FoundationFluttifyPlugin